### ISSUE TITLE
Task: Research how we can ensure file integrity through transfers in space.

### ISSUE THREAD

**Issue by karppa404** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#17] opened 2023-12-07 15:57 UTC
Figure out how we ensure the contents of the file are well written.
[User Story #12](https://github.com/orgs/Allen-ISD-Computer-Science/projects/9/views/2?pane=issue&itemId=46664249)

**Comment by Fangedan** [comment] 2024-01-23 16:19
There are two main issues we will face when ensuring file integrity through transfers in space: 

1. Data corruption through cosmic/gamma rays 
2. Checking that files do not become corrupted after transfers

## **Data corruption through cosmic/gamma rays**

The first step to data integrity (or how we are going to transfer data) is being aware of environmental issues **BEFORE** transferring files. In outer space, the transfer of data can become corrupted by astronomical objects that have a changing magnetic field, such as the planets and our Sun. 

Data pictured below show emissions from a variety of sources including radio bursts from the Sun, the Earth, and even from Jupiter's ionosphere whose wavelengths measure about fifteen meters in length. The far right of this graph shows radio bursts from the Sun caused by electrons that have been ejected into space during solar flares moving at 20% of the speed of light.

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024/assets/89644316/8f33f817-8fef-43c9-b777-1741909649e5)

Transferring data is oftentimes ill-advised in the presence of extreme radio waves such as these, and resulting files are often riddled with “noise,” or data that’s corrupted, distorted, or otherwise meaningless.

### Solution: Cosmic-ray Observatory

A cosmic-ray observatory is a scientific installation built to detect high-energy-particles coming from space called cosmic rays. This typically includes photons (high-energy light), electrons, protons, and some heavier nuclei, as well as antimatter particles. About 90% of cosmic rays are protons, 9% are alpha particles, and the remaining ~1% are other particles. For our purposes, it will be able to detect the disrupting radio waves. When we detect a spike in the waves, it is unsafe to transfer data (we will not), and vice versa (no waves = safe transfer).

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024/assets/89644316/91028d59-c58e-4b5b-9aa8-32cdbe74ad54)

> Sources: 
https://science.nasa.gov/ems/05_radiowaves/ 
https://en.wikipedia.org/wiki/Cosmic-ray_observatory

**Closed as completed** 2024-03-05 16:30 UTC
Labels: sprint-7, sprint-8, SPRINT-9
